language: go
sudo: required
dist: trusty

go:
  - 1.5

env:
  - DOCKER_TAG=$TRAVIS_TAG

before_install:
  - sudo apt-get update
  - sudo apt-get install -y librados-dev librbd-dev

install:
  - go get github.com/ceph/go-ceph
  - go get github.com/prometheus/client_golang/prometheus
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

script:
  - go test -coverprofile=collectors.coverprofile ./collectors
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service travis-ci
  - docker build -t digitalocean/ceph_exporter .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push digitalocean/ceph_exporter:$DOCKER_TAG;
    fi
